// components/campoParaAba.ts

export const campoParaAba: Record<string, string> = {
  // 🗂️ Dados Cadastrais
  tipo: 'dadosCadastrais',
  cpfcgc: 'dadosCadastrais',
  email: 'dadosCadastrais',
  nome: 'dadosCadastrais',
  nomefant: 'dadosCadastrais',
  mesmoendcobr: 'dadosCadastrais',
  cep: 'dadosCadastrais',
  ender: 'dadosCadastrais',
  numero: 'dadosCadastrais',
  bairro: 'dadosCadastrais',
  cidade: 'dadosCadastrais',
  uf: 'dadosCadastrais',
  codpais: 'dadosCadastrais',
  complemento: 'dadosCadastrais',
  referencia: 'dadosCadastrais',
  tipocliente: 'dadosCadastrais',
  sit_tributaria: 'dadosCadastrais',
  tipoemp: 'dadosCadastrais',
  classecliente: 'dadosCadastrais',
  isentoim: 'dadosCadastrais',
  isentoie: 'dadosCadastrais',
  isentosuf: 'dadosCadastrais',
  imun: 'dadosCadastrais',
  iest: 'dadosCadastrais',
  isuframa: 'dadosCadastrais',
  habilitasuframa: 'dadosCadastrais',
  obs: 'dadosCadastrais',

  // 📦 Dados Comerciais
  acrescimo: 'dadosComerciais',
  desconto: 'dadosComerciais',
  kickback: 'dadosComerciais',
  prvenda: 'dadosComerciais',
  bloquear_preco: 'dadosComerciais',

  // 💰 Dados Financeiros
  limite: 'dadosFinanceiros',
  status: 'dadosFinanceiros',
  claspgto: 'dadosFinanceiros',
  aceitaratraso: 'dadosFinanceiros',
  atraso: 'dadosFinanceiros',
  icms: 'dadosFinanceiros',
  faixafin: 'dadosFinanceiros',
  banco: 'dadosFinanceiros',
  cepcobr: 'dadosFinanceiros',
  endercobr: 'dadosFinanceiros',
  numerocobr: 'dadosFinanceiros',
  bairrocobr: 'dadosFinanceiros',
  cidadecobr: 'dadosFinanceiros',
  ufcobr: 'dadosFinanceiros',
  codpaiscobr: 'dadosFinanceiros',
  complementocobr: 'dadosFinanceiros',
  referenciacobr: 'dadosFinanceiros',
};
